basePath: /
definitions:
  types.GetTaskResultHandlerResponse:
    properties:
      result:
        type: string
    type: object
  types.GetTaskStatusHandlerResponse:
    properties:
      status:
        type: string
    type: object
  types.PostTaskHandlerRequest:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  types.PostTaskHandlerResponse:
    properties:
      taskId:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is homework server.
  title: Homework1
  version: "1.0"
paths:
  /result:
    get:
      consumes:
      - application/json
      description: Get task result by its id
      parameters:
      - in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetTaskResultHandlerResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get task result
      tags:
      - task
  /status:
    get:
      consumes:
      - application/json
      description: Get task status by its id
      parameters:
      - in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetTaskStatusHandlerResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get task status
      tags:
      - task
  /task:
    delete:
      consumes:
      - application/json
      description: Delete task by its id
      parameters:
      - in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Task deleted successfully
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Delete task
      tags:
      - task
    post:
      consumes:
      - application/json
      description: Create new task with the specified id and result
      parameters:
      - description: Task creation data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.PostTaskHandlerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PostTaskHandlerResponse'
        "400":
          description: Bad request
          schema:
            type: string
      summary: Create task
      tags:
      - task
swagger: "2.0"
